# -*- coding: utf-8 -*-
"""Mapa_Henon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J5Ur1R4sMvby__H0G-5lJCmf4RQdmyua
"""

import numpy as np
import matplotlib.pyplot as plt

x_0 = 0
y_0 = 0

def map(x,y):
  a = 1.4
  b = 0.3
  x_1 = a - x**2 + y
  y_1 = b*x
  return x_1,y_1

x_list=[]
y_list=[]
N = np.arange(0,10**7,1)

for i in N:
  x_0, y_0 = map(x_0,y_0)
  x_list.append(x_0)
  y_list.append(y_0)

plt.style.use('seaborn-pastel')

#plt.xlim([0.4,0.7])
#plt.ylim([-0.28,-0.12])
plt.title('Mapa de Henon (a = 1.4, b = 0.3)')
plt.xlabel('x')
plt.ylabel('y')
plt.plot(x_list,y_list,'b.', marker=',')
plt.show()